import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import DictionaryProvider from '@/dictionary-provider';
import { getDictionary } from '@/get-dictionary';
import { cookies } from 'next/headers';
import { LanguagesEnum } from '@/interfaces';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: LanguagesEnum } }) {
  const dictionary = await getDictionary(params.lang);
  const cookieStore = cookies();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DictionaryProvider dictionary={dictionary}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
