import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
// import 'slick-carousel/slick/slick-theme.css'; // Removed to avoid font loading issues
import './globals.scss';
import DictionaryProvider from '@/dictionary-provider';
import { getDictionary } from '@/get-dictionary';
import { LanguagesEnum } from '@/interfaces';
import Heading from './components/Heading';
import Footer from './components/Footer';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: LanguagesEnum } }) {
  const dictionary = await getDictionary(params.lang);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DictionaryProvider dictionary={dictionary}>
          <Heading />
          {children}
          <Footer />
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff',
              },
              success: {
                duration: 3000,
                iconTheme: {
                  primary: '#4ade80',
                  secondary: '#fff',
                },
              },
              error: {
                duration: 4000,
                iconTheme: {
                  primary: '#ef4444',
                  secondary: '#fff',
                },
              },
            }}
          />
        </DictionaryProvider>
      </body>
    </html>
  );
}
